---

name: CI

on:
  push:
    branches: [main, uv-debug]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          # See https://github.com/codecov/codecov-action/issues/190.
          fetch-depth: 2

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # We do not use the cache action as uv is faster than the cache action.
      - name: "Setup uv and venv"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv /home/runner/.venv
          source /home/runner/.venv/bin/activate

      - name: "Install dependencies"
        run: uv pip install -v --upgrade --editable .[dev]
